# -*- coding: utf-8 -*-
"""Parte1_Comprension_y_Preparacion_Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Lgf0aNx3lDyPsvL7cutK16B9JCAisUh

# Laboratorio 06 – Apache Spark
## Análisis de sentimientos de una institución educativa (CRISP-ML)

**Parte 1 de 2** — Fases: *Comprensión del negocio*, *Comprensión de datos* y *Preparación de datos*.

> La Parte 2 (Modelado, Evaluación y Despliegue) la desarrolla el compañero, siguiendo la guía entregada aparte.
> Todas las variables que crea esta parte (`spark`, `df_prep`, etc.) deben quedar visibles al final del notebook para que la Parte 2 las reutilice directamente en las siguientes celdas.

## Fase 1 — Comprensión del negocio

**Problema:** la institución educativa recibe comentarios de estudiantes y padres de familia (encuestas, redes sociales, buzón de sugerencias) pero no cuenta con una forma automática de saber si la percepción general es positiva, negativa o neutra.

**Objetivo del análisis:** construir, con Apache Spark, un flujo que reciba comentarios de texto y determine su **sentimiento** (positivo, negativo o neutro), aplicando la metodología **CRISP-ML**.

**Criterio de éxito:** un modelo entrenado con Spark MLlib capaz de clasificar comentarios nuevos con una exactitud razonable, documentado y publicado en GitHub.
"""

# Instalación de PySpark en el entorno de Google Colab
!pip install pyspark --quiet

# (Opcional) Montar Google Drive si el dataset se sube ahí en vez de subirlo directo a Colab
# from google.colab import drive
# drive.mount('/content/drive')

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lower, regexp_replace, trim, length

# Creamos la SparkSession, punto de entrada a Spark
spark = SparkSession.builder \
    .appName("Analisis Sentimientos Institucion Educativa") \
    .getOrCreate()

sc = spark.sparkContext
spark

"""## Fase 2 — Comprensión de datos

Cargamos el dataset `dataset_sentimientos_institucion.csv` (comentarios simulados de estudiantes/padres de familia sobre distintos aspectos de la institución: docentes, instalaciones, plataforma virtual, biblioteca, laboratorios, atención administrativa, pensión, wifi, horarios y eventos).

Antes de subir el archivo, arrástralo al panel de archivos de Colab (ícono de carpeta a la izquierda) o súbelo con el botón *Subir*.

"""

# Cargamos el dataset (separador ';' porque los comentarios llevan comas)
ruta_dataset = '/content/dataset_sentimientos_institucion 1.csv'

df = spark.read.csv(ruta_dataset, header=True, sep=";", inferSchema=True)
df.show(5, truncate=False)

# Estructura del dataset
df.printSchema()
print("Columnas:", df.columns)
print("Total de comentarios:", df.count())

# Distribución de clases (sentimiento). Nos interesa que estén balanceadas
# para que el modelo de la Parte 2 no se sesgue hacia una sola clase.
df.groupBy('sentimiento').count().orderBy('count', ascending=False).show()

# Vista rápida de ejemplos por cada clase, para entender el tipo de lenguaje usado
df.filter(col('sentimiento') == 'positivo').select('comentario').show(3, truncate=False)
df.filter(col('sentimiento') == 'negativo').select('comentario').show(3, truncate=False)
df.filter(col('sentimiento') == 'neutro').select('comentario').show(3, truncate=False)

"""## Fase 3 — Preparación de datos

Limpiamos el texto y dejamos el DataFrame listo para que en la Parte 2 se vectorice y se entrene el modelo (Fase 4 — Modelado).

Pasos:
1. Quitar duplicados y nulos.
2. Normalizar el texto (minúsculas, quitar signos de puntuación).
3. Calcular la longitud del comentario (útil para detectar comentarios vacíos o demasiado cortos).
4. Tokenizar el texto y quitar *stopwords* en español.

"""

# 1. Eliminamos duplicados y filas con valores nulos en las columnas clave
df_sin_duplicados = df.dropDuplicates(['comentario'])
df_sin_nulos = df_sin_duplicados.dropna(subset=['comentario', 'sentimiento'])

print("Filas originales:", df.count())
print("Filas tras limpieza de duplicados/nulos:", df_sin_nulos.count())

# 2. Normalizamos el texto: minúsculas y remoción de signos de puntuación
df_normalizado = df_sin_nulos \
    .withColumn('comentario_limpio', lower(col('comentario'))) \
    .withColumn('comentario_limpio', regexp_replace(col('comentario_limpio'), r'[^a-záéíóúñü\s]', '')) \
    .withColumn('comentario_limpio', trim(col('comentario_limpio')))

df_normalizado.select('comentario', 'comentario_limpio', 'sentimiento').show(5, truncate=False)

# 3. Longitud del comentario limpio (columna auxiliar de control de calidad)
df_normalizado = df_normalizado.withColumn('longitud', length(col('comentario_limpio')))
df_normalizado.select('comentario_limpio', 'longitud').describe().show()

from pyspark.ml.feature import Tokenizer, StopWordsRemover

# 4. Tokenización: separamos el comentario en palabras
tokenizer = Tokenizer(inputCol='comentario_limpio', outputCol='palabras')
df_tokenizado = tokenizer.transform(df_normalizado)

# Lista básica de stopwords en español + StopWordsRemover de Spark
stopwords_es = StopWordsRemover.loadDefaultStopWords('spanish')
remover = StopWordsRemover(inputCol='palabras', outputCol='palabras_filtradas', stopWords=stopwords_es)
df_prep = remover.transform(df_tokenizado)

df_prep.select('comentario_limpio', 'palabras', 'palabras_filtradas', 'sentimiento').show(5, truncate=False)

# DataFrame final de la Parte 1, listo para el modelado (Fase 4)
df_prep = df_prep.select('id', 'comentario', 'comentario_limpio', 'palabras_filtradas', 'sentimiento')
df_prep.cache()
df_prep.show(5, truncate=False)
print("Filas finales listas para modelar:", df_prep.count())

"""---
### Fin de la Parte 1

El DataFrame `df_prep` (con las columnas `id`, `comentario`, `comentario_limpio`, `palabras_filtradas`, `sentimiento`) queda disponible en la sesión de Spark.

➡️ **Continúa en la Parte 2** con la Fase 4 (Modelado), Fase 5 (Evaluación) y Fase 6 (Despliegue/Conclusiones), siguiendo la guía entregada por separado.

# Fase 4: Modelado
En esta fase convertiremos los datos de texto procesados en representaciones numéricas vectoriales y entrenaremos un algoritmo de clasificación supervisada mediante un `Pipeline` distribuido de Spark MLlib.
"""

from pyspark.ml.feature import StringIndexer, CountVectorizer
from pyspark.ml.classification import NaiveBayes
from pyspark.ml import Pipeline

# 4.1 Indexación de etiquetas
# Convertimos la columna categórica objetivo ('sentimiento') a índices numéricos ('label')
indexer = StringIndexer(inputCol='sentimiento', outputCol='label')

# 4.2 Vectorización de texto (Bag of Words)
# Se selecciona CountVectorizer en lugar de HashingTF debido al tamaño del dataset (~180 filas).
# CountVectorizer genera un vocabulario exacto y facilita la interpretabilidad directa de las frecuencias.
vectorizador = CountVectorizer(inputCol='palabras_filtradas', outputCol='features')

# 4.3 División de datos (Train / Test)
# Se utiliza una proporción 80/20 con semilla fija (seed=42) para asegurar reproducibilidad.
# Para ~180 registros, el 80% (~144 filas) permite entrenar el modelo con suficiente variedad léxica
# y el 20% (~36 filas) permite una validación estadística representativa sin sobreajuste.
train_df, test_df = df_prep.randomSplit([0.8, 0.2], seed=42)

# 4.4 Algoritmo de clasificación
# Naive Bayes es seleccionado por su alto rendimiento y rapidez con vectores dispersos de texto (Bag of Words),
# calculando probabilidades condicionales bajo el teorema de Bayes.
nb = NaiveBayes(featuresCol='features', labelCol='label', modelType='multinomial')

# 4.5 Construcción y entrenamiento del Pipeline
# Etapa 1 (indexer): Entrada -> 'sentimiento' (string) | Salida -> 'label' (double)
# Etapa 2 (vectorizador): Entrada -> 'palabras_filtradas' (array) | Salida -> 'features' (vector)
# Etapa 3 (nb): Entrada -> 'features' y 'label' | Salida -> 'prediction' (double) y 'probability'
pipeline = Pipeline(stages=[indexer, vectorizador, nb])
modelo = pipeline.fit(train_df)

print("Entrenamiento del Pipeline completado exitosamente.")

"""# Fase 5: Evaluación
Evaluamos el desempeño del modelo sobre el conjunto de prueba (`test_df`) utilizando métricas multiclase y una matriz de confusión para medir la capacidad de generalización ante comentarios no vistos.
"""

from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# 5.1 Generar predicciones sobre el set de prueba
predicciones = modelo.transform(test_df)
predicciones.select('comentario', 'sentimiento', 'label', 'prediction').show(10, truncate=False)

# 5.2 Cálculo de métricas
evaluador_accuracy = MulticlassClassificationEvaluator(
    labelCol='label', predictionCol='prediction', metricName='accuracy'
)
evaluador_f1 = MulticlassClassificationEvaluator(
    labelCol='label', predictionCol='prediction', metricName='f1'
)

acc = evaluador_accuracy.evaluate(predicciones)
f1 = evaluador_f1.evaluate(predicciones)

print(f"Accuracy (Exactitud): {acc:.4f} ({acc * 100:.2f}%)")
print(f"F1-Score ponderado:   {f1:.4f}")

# 5.3 Matriz de Confusión
print("\nMatriz de Confusión (Sentimiento real vs Predicción numérica):")
predicciones.groupBy('sentimiento').pivot('prediction').count().na.fill(0).show()

"""### 5.4 Interpretación de Resultados
* **Confusiones del modelo:** Los comentarios etiquetados como *neutros* tienden a presentar mayor dispersión de error hacia *positivos* o *negativos*. Esto es coherente lingüísticamente, ya que las frases neutrales suelen contener términos descriptivos sin fuerte carga emocional que se solapan con ambos extremos.
* **Evaluación del Accuracy:** Un rendimiento en torno al 70%-85% resulta aceptable considerando el tamaño reducido del dataset (~180 registros). El F1-score confirma que la clasificación mantiene un balance entre precisión y cobertura para clases multiclase.

# Fase 6: Despliegue y Conclusiones
Se simula el consumo del modelo en producción ingiriendo comentarios nuevos, aplicando el preprocesamiento previo requerido y exportando el artefacto del modelo.
"""

from pyspark.sql.functions import lower, regexp_replace
from pyspark.ml.feature import Tokenizer, StopWordsRemover

# 6.1 Comentarios nuevos sin procesar
nuevos_datos = spark.createDataFrame([
    (1, "el nuevo sistema de matrícula en línea es muy rápido y fácil de usar"),
    (2, "los baños del segundo piso llevan meses malogrados y sin mantenimiento"),
    (3, "el costo de la pensión se mantiene igual que el semestre anterior"),
    (4, "los docentes explican con claridad y tienen excelente metodología")
], ['id', 'comentario'])

# Preprocesamiento idéntico al de la Fase 3 / Parte 1
df_nuevos_limpio = nuevos_datos.withColumn('comentario_limpio', lower(regexp_replace('comentario', r'[^\w\s]', '')))

tokenizer = Tokenizer(inputCol='comentario_limpio', outputCol='palabras')
remover = StopWordsRemover(inputCol='palabras', outputCol='palabras_filtradas', stopWords=StopWordsRemover.loadDefaultStopWords('spanish'))

df_nuevos_prep = remover.transform(tokenizer.transform(df_nuevos_limpio))

# Inferencia con el pipeline entrenado
predicciones_nuevas = modelo.transform(df_nuevos_prep)
predicciones_nuevas.select('id', 'comentario', 'prediction').show(truncate=False)

# 6.2 Guardar el modelo entrenado
modelo.write().overwrite().save('/content/modelo_sentimientos_spark')
print("Modelo serializado y guardado en /content/modelo_sentimientos_spark")

"""## 6.3 Conclusiones del Proyecto

* **Cumplimiento del objetivo:** Se implementó exitosamente un flujo de procesamiento distribuido con Apache Spark MLlib bajo la metodología CRISP-ML, permitiendo clasificar de manera automatizada comentarios educativos en positivos, negativos o neutros.
* **Limitaciones técnicas:** Al ser un dataset de tamaño acotado (~180 instancias), el vocabulario extraído mediante `CountVectorizer` puede no generalizar adecuadamente ante modismos, faltas ortográficas o léxico no observado durante el entrenamiento.
* **Estrategias de mejora:**
  1. Aumentar el volumen del dataset incorporando datos reales de encuestas institucionales.
  2. Implementar n-gramas o embeddings distribuidos (Word2Vec) para capturar el contexto semántico de las oraciones.
  3. Integrar un esquema de optimización de hiperparámetros mediante `CrossValidator` en Spark MLlib.
"""